# Default values for e-commerce-admin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: e-commerce

image:
  repository: containerregistryunique.azurecr.io/e-admin
  pullPolicy: IfNotPresent
  tag: "0.1.5"

imagePullSecrets:
  - name: acr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: "azure-application-gateway"
  annotations:
    kubernetes.io/ingress.class: "azure-application-gateway"

  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - e-commerce-admin
        topologyKey: "kubernetes.io/hostname"

env:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "NEXT-PUBLIC-CLERK-PUBLISHABLE-KEY"
  CLERK_SECRET_KEY: "CLERK-SECRET-KEY"
  NEXT_PUBLIC_CLERK_SIGN_IN_URL: "NEXT-PUBLIC-CLERK-SIGN-IN-URL"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: "NEXT-PUBLIC-CLERK-AFTER-SIGN-IN-URL"
  DATABASE_URL: "DATABASE-URL"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "NEXT-PUBLIC-CLOUDINARY-CLOUD-NAME"
  NEXT_PUBLIC_CLERK_SIGN_UP_URL: "NEXT-PUBLIC-CLERK-SIGN-UP-URL"
  NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: "NEXT-PUBLIC-CLERK-AFTER-SIGN-UP-URL"
  CLOUDINARY_PRESET_NAME: "CLOUDINARY-PRESET-NAME"
  FRONTEND_STORE_URL: "FRONTEND-STORE-URL"
  STRIPE_API_KEY: "STRIPE-API-KEY"
  STRIPE_WEBHOOK_SECRET: "STRIPE-WEBHOOK-SECRET"
  NEXT_PUBLIC_API_URL: "NEXT-PUBLIC-API-URL"

secrets:
  secretName: "keyvault-secrets"
